### ISSUE TITLE
Inconsistent contextualization of Grantha ṣṭa

### ISSUE THREAD

**Issue by dscorbett** [notofonts/grantha#2]
### Font
NotoSansGrantha-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/8b6bb327cc8cc7cfd98e4d93ffdf82fe54993b17/phaseIII_only/unhinted/otf/NotoSansGrantha/NotoSansGrantha-Regular.otf
Date: 2018-10-02

### Font version
Version 2.000

### Issue
In some contexts, 'rlig' truncates the bottom right of <i>ṣṭa</i> ligature to make room for a descender in the following cluster. The lookup is incomplete and misses some contexts.

### Character data
𑌷𑍍𑌟𑌙𑍍𑌕𑌿 𑌷𑍍𑌟𑌨𑍍𑌮𑌿 𑌷𑍍𑌟𑍦𑌗 𑌷𑍍𑌟𑌀𑌗 𑌷𑍍𑌟𑌁𑌗 𑌷𑍍𑌟𑍍‍𑌗

U+11337 GRANTHA LETTER SSA
U+1134D GRANTHA SIGN VIRAMA
U+1131F GRANTHA LETTER TTA
U+11319 GRANTHA LETTER NGA
U+1134D GRANTHA SIGN VIRAMA
U+11315 GRANTHA LETTER KA
U+1133F GRANTHA VOWEL SIGN I

U+11337 GRANTHA LETTER SSA
U+1134D GRANTHA SIGN VIRAMA
U+1131F GRANTHA LETTER TTA
U+11328 GRANTHA LETTER NA
U+1134D GRANTHA SIGN VIRAMA
U+1132E GRANTHA LETTER MA
U+1133F GRANTHA VOWEL SIGN I

U+11337 GRANTHA LETTER SSA
U+1134D GRANTHA SIGN VIRAMA
U+1131F GRANTHA LETTER TTA
U+11366 COMBINING GRANTHA DIGIT ZERO
U+11317 GRANTHA LETTER GA

U+11337 GRANTHA LETTER SSA
U+1134D GRANTHA SIGN VIRAMA
U+1131F GRANTHA LETTER TTA
U+11300 GRANTHA SIGN COMBINING ANUSVARA ABOVE
U+11317 GRANTHA LETTER GA

U+11337 GRANTHA LETTER SSA
U+1134D GRANTHA SIGN VIRAMA
U+1131F GRANTHA LETTER TTA
U+11301 GRANTHA SIGN CANDRABINDU
U+11317 GRANTHA LETTER GA

U+11337 GRANTHA LETTER SSA
U+1134D GRANTHA SIGN VIRAMA
U+1131F GRANTHA LETTER TTA
U+1134D GRANTHA SIGN VIRAMA
U+200D ZERO WIDTH JOINER
U+11317 GRANTHA LETTER GA

### Screenshot
![𑌷𑍍𑌟𑌙𑍍𑌕𑌿 𑌷𑍍𑌟𑌨𑍍𑌮𑌿 𑌷𑍍𑌟𑍦𑌗 𑌷𑍍𑌟𑌀𑌗 𑌷𑍍𑌟𑌁𑌗 𑌷𑍍𑌟𑍍‍𑌗](https://user-images.githubusercontent.com/1124347/46424217-8337bf00-c706-11e8-8b10-5e269249d702.png)

**Comment by SKing-2003** [comment]
If I understand the issue correctly, this seems to be fixed in the most recent build:
![image](https://user-images.githubusercontent.com/107930743/175045542-32329768-bea7-4d52-b80e-a260caa51699.png)
