### ISSUE TITLE
No advance width for vocalic R

### ISSUE THREAD

**Issue by miloush** [notofonts/grantha#21]
### Title 
Some of the glyphs for vocalic R and RR seem to have zero advance width, causing glyphs to overlap.

### Font 
NotoSerifGrantha-Regular.ttf

### Where the font came from, and when
Noto website, 2023-12-19

### Font Version
Noto Serif Grantha Regular 2.004; ttfautohint (v1.8.4.7-5d5b)

### OS name and version
Windows 11 (26016.1000.amd64fre.rs_prerelease.231208-1532)

### Application name and version
dwrite.dll 10.0.26016.1000 (WinBuild.160101.0800)

### Character data
𑌕𑍍𑌯𑍃𑌕

Hex | Dec | Name | Range | C# | HTML | URL
-- | -- | -- | -- | -- | -- | --
U+11315 | 70421 | GRANTHA LETTER KA | Grantha | \U00011315 | &#x11315; | %F0%91%8C%95
U+1134D | 70477 | GRANTHA SIGN VIRAMA | Grantha | \U0001134d | &#x1134d; | %F0%91%8D%8D
U+1132F | 70447 | GRANTHA LETTER YA | Grantha | \U0001132f | &#x1132f; | %F0%91%8C%AF
U+11343 | 70467 | GRANTHA VOWEL SIGN VOCALIC R | Grantha | \U00011343 | &#x11343; | %F0%91%8D%83
U+11315 | 70421 | GRANTHA LETTER KA | Grantha | \U00011315 | &#x11315; | %F0%91%8C%95

### Screenshot
![image](https://github.com/notofonts/grantha/assets/10546952/25ef071c-2c61-4d74-970a-4f8900813dc6)

Same for U+11344 vocalic RR

**Comment by simoncozens** [comment]
Thanks for this report! It looks like it has always been the case, and affects Sans too. I'll work on it.
