### ISSUE TITLE
Number of -ya in clusters indistinguishable

### ISSUE THREAD

**Issue by miloush** [notofonts/grantha#22]
### Title 
Arbitrary number of ya is allowed in a cluster. However, any number of them looks the same to the user, potentially having security implications.

### Font 
NotoSerifGrantha-Regular.ttf

### Where the font came from, and when
Noto website, 2023-12-19

### Font Version
Noto Serif Grantha Regular 2.004; ttfautohint (v1.8.4.7-5d5b)

### OS name and version
Windows 11 (26016.1000.amd64fre.rs_prerelease.231208-1532)

### Application name and version
dwrite.dll 10.0.26016.1000 (WinBuild.160101.0800)

### Character data
𑌕𑍍𑌯𑍍𑌯𑍍𑌯𑍍𑌯𑍍𑌯

Hex | Dec | Name | Range | C# | HTML | URL
-- | -- | -- | -- | -- | -- | --
U+11315 | 70421 | GRANTHA LETTER KA | Grantha | \U00011315 | &#x11315; | %F0%91%8C%95
U+1134D | 70477 | GRANTHA SIGN VIRAMA | Grantha | \U0001134d | &#x1134d; | %F0%91%8D%8D
U+1132F | 70447 | GRANTHA LETTER YA | Grantha | \U0001132f | &#x1132f; | %F0%91%8C%AF
U+1134D | 70477 | GRANTHA SIGN VIRAMA | Grantha | \U0001134d | &#x1134d; | %F0%91%8D%8D
U+1132F | 70447 | GRANTHA LETTER YA | Grantha | \U0001132f | &#x1132f; | %F0%91%8C%AF

...

### Screenshot
![image](https://github.com/notofonts/grantha/assets/10546952/e2a2d09a-152c-4217-a37f-e40347c8ac29)

(an example of a font with better behavior on the left)

**Comment by jamadagni** [comment]
Arbitrary number of YA doesn't occur in properly formed Samskrita (or any other language) text. That said, you might want to fix this nevertheless considering the security implications.

**Comment by simoncozens** [comment]
Thanks for this report. I'm amused by the idea of a security vulnerability caused by the confusion of the number of YAs in a Sanskrit text, but I guess it could happen. :-) The only problem is that I've looked into this and the current implementation of the font is so complicated that I don't know how to fix it. I've found a potential way but it breaks other things. The best approach is going to be to throw out the existing layout code and start again.

**Comment by miloush** [comment]
From the user point of view the concern is that you will type the character twice by mistake without noticing and then text search will not find it. Whether the issue justifies complete redesign of the layout code is not up to me to say, I can imagine this case not to be the highest priority.
