### ISSUE TITLE
No advance width for repha breaked out of a cluster

### ISSUE THREAD

**Issue by miloush** [notofonts/grantha#23]
### Title 
When mutiple rephas cause consonants to split out of a cluster, the RA glyph has zero advance width.

### Font 
NotoSerifGrantha-Regular.ttf

### Where the font came from, and when
Noto website, 2023-12-19

### Font Version
Noto Serif Grantha Regular 2.004; ttfautohint (v1.8.4.7-5d5b)

### OS name and version
Windows 11 (26016.1000.amd64fre.rs_prerelease.231208-1532)

### Application name and version
dwrite.dll 10.0.26016.1000 (WinBuild.160101.0800)

### Character data
𑌕𑍍𑌰𑍍𑌰𑍍𑌰𑍍𑌰

Hex | Dec | Name | Range | C# | HTML | URL
-- | -- | -- | -- | -- | -- | --
U+11315 | 70421 | GRANTHA LETTER KA | Grantha | \U00011315 | &#x11315; | %F0%91%8C%95
U+1134D | 70477 | GRANTHA SIGN VIRAMA | Grantha | \U0001134d | &#x1134d; | %F0%91%8D%8D
U+11330 | 70448 | GRANTHA LETTER RA | Grantha | \U00011330 | &#x11330; | %F0%91%8C%B0
U+1134D | 70477 | GRANTHA SIGN VIRAMA | Grantha | \U0001134d | &#x1134d; | %F0%91%8D%8D
U+11330 | 70448 | GRANTHA LETTER RA | Grantha | \U00011330 | &#x11330; | %F0%91%8C%B0
U+1134D | 70477 | GRANTHA SIGN VIRAMA | Grantha | \U0001134d | &#x1134d; | %F0%91%8D%8D
U+11330 | 70448 | GRANTHA LETTER RA | Grantha | \U00011330 | &#x11330; | %F0%91%8C%B0
U+1134D | 70477 | GRANTHA SIGN VIRAMA | Grantha | \U0001134d | &#x1134d; | %F0%91%8D%8D
U+11330 | 70448 | GRANTHA LETTER RA | Grantha | \U00011330 | &#x11330; | %F0%91%8C%B0

### Screenshot
![image](https://github.com/notofonts/grantha/assets/10546952/720eaa25-efa3-441d-b195-939ca8d5e5ea)

(an example of font with better handling on the left)

**Comment by simoncozens** [comment]
I think this is not really a font issue. Harfbuzz (Linux/Android) and CoreText (OS X) allow arbitrary numbers of rephas and so the repha is never "broken out of a cluster":

![shape](https://github.com/notofonts/grantha/assets/106728/d1f0038f-582e-4698-b91f-d64187545a44)

It seems like Windows is not forming ra-vattu at all.
