### ISSUE TITLE
Sloppy contextualization of Grantha letters with descenders

### ISSUE THREAD

**Issue by dscorbett** [notofonts/grantha#4]
### Font
NotoSansGrantha-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/8b6bb327cc8cc7cfd98e4d93ffdf82fe54993b17/phaseIII_only/unhinted/otf/NotoSansGrantha/NotoSansGrantha-Regular.otf
Date: 2018-10-02

### Font version
Version 2.000

### Issue
In certain contexts, glyphs with downwards-curling descenders are replaced with variants with flat descenders. When an unexpected mark (like an anusvara above) intervenes, the substitution fails to apply. The substitution overapplies too: when two glyphs that have flattened variants appear in the context of a rule of the lookup, sometimes both of them are substituted with their flattened variants, instead of just the one that needs it.

### Character data
𑌨𑍍𑌦𑌀𑌗
𑌗𑍍𑌗𑌨𑍍𑌤

U+11328 GRANTHA LETTER NA
U+1134D GRANTHA SIGN VIRAMA
U+11326 GRANTHA LETTER DA
U+11300 GRANTHA SIGN COMBINING ANUSVARA ABOVE
U+11317 GRANTHA LETTER GA

U+11317 GRANTHA LETTER GA
U+1134D GRANTHA SIGN VIRAMA
U+11317 GRANTHA LETTER GA
U+11328 GRANTHA LETTER NA
U+1134D GRANTHA SIGN VIRAMA
U+11324 GRANTHA LETTER TA

### Screenshot
![𑌨𑍍𑌦𑌀𑌗 𑌗𑍍𑌗𑌨𑍍𑌤](https://user-images.githubusercontent.com/1124347/46566745-90190600-c8f2-11e8-8a8c-e5513f170cbf.png)

**Comment by simoncozens** [comment]
I can't see what's wrong with this. This looks okay:
![shape](https://user-images.githubusercontent.com/106728/187067744-33370a65-2402-42b7-be49-53c3f2c24076.png)

No tails are flattened with/without the anusvara, but I'm not sure I would expect them to be.

**Comment by jamadagni** [comment]
Was the intention to remove descenders in the case of mainline consonants with below-base consonants? Only that makes sense. What does the anusvara have to do with it?

**Comment by punchcutter** [comment]
Anusvara is only relevant for shaping engines and the substitution code that should ignore the anusvara when doing the substitution. The intention was for tails to go away only if they will collide with a previous below base form. There is also a stylistic set to remove all tails so that everything is more visually consistent, but thinking about it now it might make more sense and look nicer to keep tails when "tails = on" and just adjust them to be shorter so they don't collide.

**Comment by simoncozens** [comment]
Pretty sure the issue as reported is fixed:
![shape](https://github.com/notofonts/grantha/assets/106728/2f11699d-3339-481f-962a-11e21f982cee)
